FROM eur0c.laas.fr:4567/humanoid-path-planner/hpp-doc/ubuntu:14.04

RUN export DEVEL_DIR=/builds/humanoid-path-planner/hpp-doc/workspace
RUN /auto-install-hpp.sh --branch devel --target doxygen-1.8.10.install
RUN /auto-install-hpp.sh --branch devel --target OpenSceneGraph-dae-plugin.install
RUN mv $DEVEL_DIR /clean_workspace
